name: 'Manage support request issues'

on:
  issues:
    types: [labeled, unlabeled, reopened]

jobs:
  support:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/support-requests@v3
        with:
          github-token: ${{ github.token }}
          support-label:  "Support request"
          issue-comment: >
            Hi, we only accept **bug reports** on this issue tracker, but this issue looks like a support request.


            Instead of creating an issue, try the following:

            - Check our [Documentation](https://doc.pmmp.io) to see if you can find answers there

            - Ask the community on our [Discord server](https://discord.gg/KQVR3UUCv4)


            [Discord](https://discord.gg/KQVR3UUCv4)

          close-issue: true
          lock-issue: false
